services:
  web01:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./web01:/usr/share/nginx/html
  web02:
    image: nginx:alpine
    ports:
      - "4001:80"
    volumes:
      - ./web02:/usr/share/nginx/html
